# Generated by Django 5.1.6 on 2025-06-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartelement',
            name='shopping_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_elements', to='main_app.shoppingcart', verbose_name='Корзина'),
        ),
    ]
