# Generated by Django 5.1.6 on 2025-06-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_shoppingcartelement_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.customuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='shoppingcartelement',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_elements', to='main_app.shoppingcart', verbose_name='Корзина'),
        ),
    ]
